# Generated by Django 5.1 on 2024-10-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expensiveapp', '0008_alter_product_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
