# Generated by Django 5.1 on 2024-10-30 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expensiveapp', '0009_userregister_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Expensiveapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expensiveapp.userregister')),
            ],
        ),
    ]
