# Generated by Django 5.1 on 2024-10-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expensiveapp', '0010_addcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='quantity',
            new_name='stock_status',
        ),
    ]
