# Generated by Django 5.0.6 on 2024-11-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expensiveapp', '0012_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
