# Generated by Django 5.0.2 on 2024-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expensiveapp', '0015_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
