# Generated by Django 5.0.2 on 2024-11-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expensiveapp', '0016_alter_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
